-- InSIS import: 3 courses (UPSERT)

INSERT INTO shared_courses (code, semester, data, ai_summary, status)
VALUES ('4ITCZV002', 'LS 2025/26', '{"code":"4ITCZV002","name":"Actuarial models","semester":"LS 2025/26","credits":14,"language":"angličtina","examType":"zkouška","group":"volitelny","lecturer":"Ing. Pavel Zimmermann, Ph.D.","allLecturers":["Ing. Pavel Zimmermann, Ph.D. (garant)"],"description":"Předmět je zaměřen na seznámení se základními pojmy, metodami a technikami používanými v aktuárské praxi. Obsah předmětu je vytvořen na základě sylabu Evropské aktuárské asociace (CORE SYLLABUS FOR ACTUARIAL TRAINING IN EUROPE)","learningOutcomes":["Znalost aktuárských modelů: Studenti by měli mít základní a komplexní znalost o aktuárských modelech, jejich definicích, použití a aplikacích v různých oblastech aktuárské praxe. Schopnost tvorby a analýzy modelů: Studenti by měli být schopni vytvářet aktuárské modely a provádět jejich analýzu. To zahrnuje schopnost vybrat správné statistické metody, interpretovat výsledky a předpovídat budoucí události. Statistická a matematická znalost: Studenti by měli mít pevný základ v oblasti pravděpodobnosti, statistiky a matematiky, který je nezbytný pro pochopení a aplikaci aktuárských modelů. Schopnost používat software a nástroje: Studenti by měli být seznámeni s různými aktuárskými softwarovýmni a nástroji používanými v praxi. Měli by být schopni efektivně využívat tyto nástroje pro analýzu dat, tvorbu modelů interpretaci a prezentaci jejich výsledků."],"weeklyTopics":[{"week":1,"topic":"Základy aktuárských pravděpodobnostních modelů"},{"week":2,"topic":"Zobecněné lineární modely"},{"week":3,"topic":"Modely pro naceňování pojistných smluv"},{"week":4,"topic":"Modely škodních rezerv"},{"week":5,"topic":"Zajištění"},{"week":6,"topic":"Bayesovská statistika a teorie kredibility"},{"week":7,"topic":"Úvod do životního pojištění"},{"week":8,"topic":"Tradiční aktuárské techniky - Tradiční produkty"},{"week":9,"topic":"Flexibilní životní produkty"},{"week":10,"topic":"Rozšířené životní pojištění"},{"week":11,"topic":"Reálné aktuárské projekční modely"},{"week":12,"topic":"Praktické aplikace reálných modelů"}],"workload":{"lectures":0,"seminars":0,"project":0,"testPrep":0,"examPrep":364,"total":364},"components":[{"name":"Závěrečný test","weight":50,"type":"exam","description":"","maxScore":null,"passingScore":null},{"name":"Závěrečná ústní zkouška","weight":50,"type":"exam","description":"","maxScore":null,"passingScore":null}],"gradingScale":[{"grade":"1","label":"Výborně","minPercent":90},{"grade":"2","label":"Velmi dobře","minPercent":75},{"grade":"3","label":"Dobře","minPercent":60},{"grade":"4","label":"Nedostatečně","minPercent":0}],"requirements":[],"literature":{"required":[],"recommended":["PDF výstup (PDF)Dokument RTF (RTF)"]},"schedule":[],"insisUrl":"https://insis.vse.cz/auth/katalog/syllabus.pl?zpet=/auth/katalog/index.pl?vzorek=4IT,Dohledat=Search,fakulta=31140,obdobi=381,jak=dle_jmena;predmet=214004;lang=cz","aiSummary":""}'::jsonb, '', 'validated')
ON CONFLICT ON CONSTRAINT unique_code_semester
DO UPDATE SET data = EXCLUDED.data, status = 'validated';

INSERT INTO shared_courses (code, semester, data, ai_summary, status)
VALUES ('4ITCZV006', 'LS 2025/26', '{"code":"4ITCZV006","name":"Actuarial models - Neživotní pojištění","semester":"LS 2025/26","credits":7,"language":"angličtina","examType":"zkouška","group":"volitelny","lecturer":"Ing. Pavel Zimmermann, Ph.D.","allLecturers":["Ing. Pavel Zimmermann, Ph.D. (garant)"],"description":"-- obsah této položky nebyl definován --","learningOutcomes":["obsah této položky nebyl definován --"],"weeklyTopics":[{"week":1,"topic":"-- obsah této položky nebyl definován --"}],"workload":{"lectures":0,"seminars":0,"project":0,"testPrep":0,"examPrep":0,"total":0},"components":[],"gradingScale":[{"grade":"1","label":"Výborně","minPercent":90},{"grade":"2","label":"Velmi dobře","minPercent":75},{"grade":"3","label":"Dobře","minPercent":60},{"grade":"4","label":"Nedostatečně","minPercent":0}],"requirements":[],"literature":{"required":[],"recommended":[]},"schedule":[],"insisUrl":"https://insis.vse.cz/auth/katalog/syllabus.pl?zpet=/auth/katalog/index.pl?vzorek=4IT,Dohledat=Search,fakulta=31140,obdobi=381,jak=dle_jmena;predmet=222174;lang=cz","aiSummary":""}'::jsonb, '', 'validated')
ON CONFLICT ON CONSTRAINT unique_code_semester
DO UPDATE SET data = EXCLUDED.data, status = 'validated';

INSERT INTO shared_courses (code, semester, data, ai_summary, status)
VALUES ('4ITCZV005', 'LS 2025/26', '{"code":"4ITCZV005","name":"Actuarial models - Životní pojištění","semester":"LS 2025/26","credits":7,"language":"angličtina","examType":"zkouška","group":"volitelny","lecturer":"Ing. Pavel Zimmermann, Ph.D.","allLecturers":["Ing. Pavel Zimmermann, Ph.D. (garant)"],"description":"-- obsah této položky nebyl definován --","learningOutcomes":["obsah této položky nebyl definován --"],"weeklyTopics":[{"week":1,"topic":"-- obsah této položky nebyl definován --"}],"workload":{"lectures":0,"seminars":0,"project":0,"testPrep":0,"examPrep":0,"total":0},"components":[],"gradingScale":[{"grade":"1","label":"Výborně","minPercent":90},{"grade":"2","label":"Velmi dobře","minPercent":75},{"grade":"3","label":"Dobře","minPercent":60},{"grade":"4","label":"Nedostatečně","minPercent":0}],"requirements":[],"literature":{"required":[],"recommended":[]},"schedule":[],"insisUrl":"https://insis.vse.cz/auth/katalog/syllabus.pl?zpet=/auth/katalog/index.pl?vzorek=4IT,Dohledat=Search,fakulta=31140,obdobi=381,jak=dle_jmena;predmet=222175;lang=cz","aiSummary":""}'::jsonb, '', 'validated')
ON CONFLICT ON CONSTRAINT unique_code_semester
DO UPDATE SET data = EXCLUDED.data, status = 'validated';
